<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Alex" ignored="0" name="privat-test" tests="3" failures="1" timestamp="10 фев 2018 08:19:21 GMT" time="0.059" errors="0">
  <testcase name="first" time="0.013" classname="YouTubeTest"/>
  <testcase name="second" time="0.003" classname="YouTubeTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at YouTubeTest.second(PrivatTests.java:16)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- second -->
  <testcase name="third" time="0.0" classname="YouTubeTest"/>
</testsuite> <!-- privat-test -->
