-------------------------------------------------------------------------------
Test set: privatTests.PrivatTests
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.626 s <<< FAILURE! - in privatTests.PrivatTests
second(privatTests.PrivatTests)  Time elapsed: 0.035 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [2]
	at privatTests.PrivatTests.second(PrivatTests.java:16)

