-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.698 s <<< FAILURE! - in TestSuite
second(privatTests.PrivatTests)  Time elapsed: 0.02 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [2]
	at privatTests.PrivatTests.second(PrivatTests.java:16)

